import { Sidebar } from "@components";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Explore - Popcorn Paragon",
    description: "Generated by create next app",
    keywords: "movies, tv shows, web series, movie recommendation, movie recommendation system, tv show recommendation system, movies suggestion, movie suggestion, show suggestion, series suggestion",
};


export default function ExploreLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <div className="flex">
            <Sidebar />
            {children}
        </div>
    );
}